artipie/npm-adapter

pom.xml, src/main/java/com/yegor256/npm/Meta.java, src/main/java/com/yegor256/npm/Npm.java, src/main/java/com/yegor256/npm/NpmPublishJsonToMetaBind.java, src/main/java/com/yegor256/npm/Storage.java, src/main/java/com/yegor256/npm/TgzArchive.java, src/main/java/com/yegor256/npm/package-info.java, src/test/java/com/yegor256/npm/NpmCommandsTest.java, src/test/java/com/yegor256/npm/NpmRegistry.java, src/test/resources/project-with-simple-dependency/package.json
* Design has been updated
* using qulice `0.18.19`(`new` allowed in cycles)
* NpmCommandsTest has been updated to ensure `npm install` works correctly
=> Support for npm install requirements

pom.xml, src/main/java/com/yegor256/npm/Meta.java, src/main/java/com/yegor256/npm/Npm.java, src/main/java/com/yegor256/npm/TgzArchive.java, src/test/java/com/yegor256/npm/NpmRegistry.java
@yegor256, review this pull request, please
=> Migrate to asto 0.2

README.md, pom.xml, src/main/java/com/artipie/npm/Meta.java, src/main/java/com/artipie/npm/Npm.java, src/main/java/com/artipie/npm/NpmPublishJsonToMetaBind.java, src/main/java/com/artipie/npm/TgzArchive.java, src/main/java/com/artipie/npm/package-info.java, src/test/java/com/artipie/npm/NpmCommandsTest.java, src/test/java/com/artipie/npm/NpmRegistry.java, src/test/java/com/artipie/npm/package-info.java
@yegor256 , review the Pull Request, please
=> Domain name changes: yegor256 -> artipie

.gitignore, src/main/java/com/artipie/npm/Npm.java, src/test/java/com/artipie/npm/NpmRegistry.java, src/test/resources/project-with-simple-dependency/package.json, src/test/resources/simple-npm-project/package.json
* fix temp file prefix name  - fixes #8 
* ignore node_modules/
=> Fix temp file prefix name

.travis.yml, pom.xml, src/main/java/com/artipie/npm/Meta.java, src/main/java/com/artipie/npm/Npm.java, src/main/java/com/artipie/npm/NpmPublishJsonToMetaBind.java, src/main/java/com/artipie/npm/TgzArchive.java, src/test/java/com/artipie/npm/NpmCommandsTest.java, src/test/java/com/artipie/npm/NpmRegistry.java
fixes #14 
Changes done is this pull request: the version of asto has been changed from 0.2 to 0.11. Sources have been updated according to asto changes.
=> Migrate to asto 0.11.0

.github/workflows/maven.yml, pom.xml, src/main/java/com/artipie/npm/Meta.java, src/test/java/com/artipie/npm/NpmCommandsTest.java, src/test/java/com/artipie/npm/NpmRegistry.java
=> Add latest dist tag

pom.xml, src/test/java/com/artipie/npm/NpmCommandsTest.java
* Bump asto version
* Remove test ignore on windows
=> Fix windows build

src/main/java/com/artipie/npm/Meta.java, src/main/java/com/artipie/npm/TgzRelativePath.java, src/test/java/com/artipie/npm/ReativePathTest.java, src/test/java/com/artipie/npm/RelativePathTest.java
=> Fix relative path extraction issues

src/main/java/com/artipie/npm/Meta.java
=> Update dist-tags instead of replacing

pom.xml, src/test/java/com/artipie/npm/MetaTest.java
Foe #39: created test for metadata update
=> For #39: Creating test for metadata update

pom.xml, src/main/java/com/artipie/npm/Npm.java, src/main/java/com/artipie/npm/http/NpmSlice.java, src/main/java/com/artipie/npm/http/UploadSlice.java, src/main/java/com/artipie/npm/misc/DescSortedVersions.java, src/test/java/com/artipie/npm/NpmCommandsTest.java, src/test/java/com/artipie/npm/NpmTest.java
**The main point** of this pr is to update http and asto deps. NPM adapter has problems with blocking resources, which I am considering to fix in the another pr. For now I use two different contexts of vertex, so that tests would pass. But obviously this stuff needs to be improved.
#44
=> update http and asto

pom.xml, src/main/java/com/artipie/npm/http/NpmSlice.java, src/main/java/com/artipie/npm/http/UploadSlice.java, src/main/java/com/artipie/npm/misc/JsonFromPublisher.java, src/main/java/com/artipie/npm/misc/NextSafeAvailablePort.java, src/test/java/com/artipie/npm/http/UploadSliceTest.java, src/test/java/com/artipie/npm/http/package-info.java
Test on UploadSlice: resolves #42
=> Test on UploadSlice: resolves #42

src/main/java/com/artipie/npm/http/UploadSlice.java, src/test/java/com/artipie/npm/http/UploadSliceTest.java
Closes #46 
Fixed bug with UploadSlice not saving content & not propagating errors
=> #46 - Fixed UploadSlice

pom.xml, src/main/java/com/artipie/npm/http/NpmSlice.java, src/test/java/com/artipie/npm/http/UploadSliceTest.java
#50 Basically the same code as for files-adapter
=> Issue 50: Auth added to npm adapter.

pom.xml, src/test/java/com/artipie/npm/http/UploadSliceTest.java
=> update asto to 0.20.3

src/test/java/com/artipie/npm/http/UploadSliceTest.java
Closes #54 
Updated existing `UploadSliceTest`: made it a unit tests (in my opinion there is no need to check integration with Vert.x here), fixed test logic to test code of  `UploadSlice` class
=> #54 - UploadSliceTest fixed

.github/workflows/release.yml, .release/settings.xml, npm-hosted-adapter/pom.xml, npm-proxy-adapter/pom.xml, pom.xml
#90 - fixed parent pom in child modules, added release workflow to deploy npm-adapter to central.artipie.com
=> Deploy to artipie central

npm-hosted-adapter/src/main/java/com/artipie/npm/PackageNameFromUrl.java, npm-hosted-adapter/src/main/java/com/artipie/npm/Tarballs.java, npm-hosted-adapter/src/main/java/com/artipie/npm/http/DownloadPackageSlice.java, npm-hosted-adapter/src/main/java/com/artipie/npm/http/NpmSlice.java, npm-hosted-adapter/src/main/java/com/artipie/npm/http/UploadSlice.java, npm-hosted-adapter/src/test/java/com/artipie/npm/NpmCommandsTest.java, npm-hosted-adapter/src/test/java/com/artipie/npm/TarballsTest.java, npm-hosted-adapter/src/test/java/com/artipie/npm/http/DownloadPackageSliceTest.java, npm-hosted-adapter/src/test/java/com/artipie/npm/http/UploadSliceTest.java
Closes#120 
Removed base path usage for routing, URL is used as prefix
=> #120 - Removed base path usage for routing

pom.xml, src/test/java/com/artipie/npm/NpmCommandsTest.java
Closes #68 since this question is no longer relevant
Closes #127 
Run NPM command in test container instead of local machine
=> #127 - Use testContainer

src/test/java/com/artipie/npm/NpmCommandsTest.java
Closes #129 
Closes #67 
Use `JsonFromPublisher`. Use `javax.json.JsonObject` instead of `io.vertx.core.json.JsonObject`
=> #129 - Fix NPM publish test

src/test/java/com/artipie/npm/MetaTest.java, src/test/java/com/artipie/npm/http/UploadSliceTest.java
Part of #119 
Add disabled test for time in `meta.json` to check modified time and version time.
=> #119 - Add disabled test for time in meta.json

src/test/java/com/artipie/npm/proxy/NpmProxyITCase.java
Part of #141 
NpmProxyITCase disabled
=> #141 - NpmProxyITCase disabled

pom.xml, src/main/java/com/artipie/npm/http/NpmSlice.java
Closes #140 
HTTP upgraded to 0.16.7, migrated to `BasicAuthSlice`
=> #140 - HTTP upgraded to 0.16.7, migrated to BasicAuthSlice

src/main/java/com/artipie/npm/TgzRelativePath.java, src/test/java/com/artipie/npm/RelativePathTest.java
Closes #139 
Add `.` to the regex pattern. Also delete `_` from the pattern as it is included in `\w`.
=> #139 - Fix tgz regex

src/main/java/com/artipie/npm/NpmPublishJsonToMetaSkelethon.java, src/test/java/com/artipie/npm/MetaTest.java
Closes #150 
Made `readme` and `_id` optional
=> #150 - Fix bug in meta skeleton

src/main/java/com/artipie/npm/http/GetDistTagsSlice.java, src/test/java/com/artipie/npm/http/GetDistTagsSliceTest.java
Part of #155 
Added slice for `/dist-tags` endpoint.
=> #155 - added slice for /dist-tags endpoint

src/main/java/com/artipie/npm/http/NpmSlice.java, src/test/java/com/artipie/npm/NpmDistTagsIT.java, src/test/resources/json/dist-tags.json
Part of #155 
Fully implemented `dist-tags ls` command
=> #155 - dist-tags ls fully implemented

src/main/java/com/artipie/npm/http/AddDistTagsSlice.java, src/main/java/com/artipie/npm/http/NpmSlice.java, src/test/java/com/artipie/npm/NpmDistTagsIT.java, src/test/resources/json/dist-tags.json
Part of #155 
Added IT and slice to handle `dist-tag add` command
=> #155 - dist-tags add command

src/test/java/com/artipie/npm/http/AddDistTagsSliceTest.java
Part of #155 
Added unit test for `AddDistTagsSliceTest`.
=> #155 - added unit test for AddDistTagsSliceTest

src/main/java/com/artipie/npm/http/DeleteDistTagsSlice.java, src/main/java/com/artipie/npm/http/NpmSlice.java, src/test/java/com/artipie/npm/NpmDistTagsIT.java
Part of #155 
Implemented `dist-tag rm` command
=> #155 - dist-tag rm implemented

.github/workflows/codecov.yml, README.md, pom.xml, src/main/java/com/artipie/npm/package-info.java
Closes #164 
Added codecov action, jacoco coverage metrix, badge, todo to improve code coverage.
=> #164 - code coverage

src/test/java/com/artipie/npm/http/DeleteDistTagsSliceTest.java
Closes #155 
Added unit test for `DeleteDistTagsSliceTest`
=> #155 - unit test for DeleteDistTagsSliceTest

src/main/java/com/artipie/npm/http/NpmSlice.java, src/main/java/com/artipie/npm/http/UnpublishForceSlice.java, src/test/java/com/artipie/npm/NpmUnpublishIT.java
Part of #154 
Add IT and slice without realization  for `npm unpublish`
=> #154 - Add IT and slice  for npm unpublish

pom.xml, src/main/java/com/artipie/npm/http/DeprecateSlice.java, src/main/java/com/artipie/npm/http/NpmSlice.java, src/test/java/com/artipie/npm/NpmDeprecateIT.java, src/test/resources/json/deprecated.json, src/test/resources/json/not_deprecated.json
Part of #156 
Adde IT for `npm deprecate` and dummy (for now) slice.
=> #156 - added IT and dummy slice for deprecate command

src/main/java/com/artipie/npm/http/DeprecateSlice.java, src/main/java/com/artipie/npm/http/NpmSlice.java
Part of #156 
Implemented `DeprecateSlice`.
=> #156 - implemented DeprecateSlice

src/main/java/com/artipie/npm/http/NpmSlice.java, src/main/java/com/artipie/npm/http/UnpublishForceSlice.java, src/test/java/com/artipie/npm/NpmUnpublishIT.java, src/test/java/com/artipie/npm/http/UnpublishForceSliceTest.java
Part of #154 
Implemented unpublishing of entire package
=> #154 - Entire package unpublish

src/test/java/com/artipie/npm/NpmDeprecateIT.java, src/test/java/com/artipie/npm/http/DeprecateSliceTest.java
Closes #156 
Added unit test for `DeprecateSlice` and assertion for metadata in `NpmDeprecateIT`.
=> #156 - added unite test for DeprecateSlice

pom.xml, src/test/java/com/artipie/npm/NpmIT.java, src/test/resources/json/deprecated.json
Closes #141 
Turned off resources filtering to fix npm install test.
=> #141 - resources filtering

src/main/java/com/artipie/npm/http/CurlPublish.java, src/test/java/com/artipie/npm/JsonFromMeta.java, src/test/java/com/artipie/npm/http/CurlPutIT.java, src/test/resources/storage/@hello/simple-npm-project/meta.json
Part of #36 
Add IT for `curl PUT` tgz archive
=> #36 - Add IT for curl PUT

src/test/java/com/artipie/npm/MetaUpdateByJsonTest.java, src/test/java/com/artipie/npm/http/CliPublishTest.java, src/test/resources/json/cli_publish.json, src/test/resources/json/simple-project-1.0.2.json
Part of #36 
Added unit tests for meta update by json and `CliPublish`
=> #36 - Unit tests for meta update by json and cliPublish

pom.xml, src/main/java/com/artipie/npm/http/DeprecateSlice.java, src/main/java/com/artipie/npm/http/NpmSlice.java, src/main/java/com/artipie/npm/http/UnpublishForceSlice.java, src/main/java/com/artipie/npm/http/UnpublishPutSlice.java, src/test/java/com/artipie/npm/NpmUnpublishIT.java, src/test/java/com/artipie/npm/http/UnpublishPutSliceTest.java, src/test/resources/json/unpublish.json
Part of #154
Unpublishing single version was implemented. 
Added IT for removing single version when multiple versions are published and one version is published
=> #154 - Implement unpublishing single version, add IT

pom.xml, src/main/java/com/artipie/npm/http/UnpublishPutSlice.java, src/test/java/com/artipie/npm/http/DeprecateSliceTest.java, src/test/java/com/artipie/npm/http/UnpublishPutSliceTest.java, src/test/resources/json/unpublish.json
Closes #154 
Add tests for `UnpublishPutSlice`
=> #154 - Add tests for UnpublishPutSlice

src/main/java/com/artipie/npm/Meta.java, src/test/java/com/artipie/npm/MetaTest.java
Closes #198 
Fixed bug with adding tag `latest` on first upload in case of existence user tag
=> Fix bug with adding tag `latest`

pom.xml
=> Updated asto and http

pom.xml, src/main/java/com/artipie/npm/PackageNameFromUrl.java, src/main/java/com/artipie/npm/TgzArchive.java, src/main/java/com/artipie/npm/TgzRelativePath.java, src/main/java/com/artipie/npm/http/UnpublishPutSlice.java, src/main/java/com/artipie/npm/proxy/http/NpmPath.java, src/test/java/com/artipie/npm/RelativePathTest.java, src/test/java/com/artipie/npm/TgzArchiveTest.java, src/test/java/com/artipie/npm/http/UnpublishPutSliceTest.java, src/test/java/com/artipie/npm/proxy/http/AssetPathTest.java, src/test/java/com/artipie/npm/proxy/http/PackagePathTest.java
=> Bump `asto` to 1.2.1
